USE ROLE SYSADMIN;
CREATE WAREHOUSE CH2_WH WITH WAREHOUSE_SIZE = MEDIUM AUTO_SUSPEND = 300 AUTO_RESUME = true INITIALLY_SUSPENDED = true;

USE ROLE SYSADMIN;
ALTER WAREHOUSE CH2_WH SET WAREHOUSE_SIZE = LARGE;

USE ROLE SYSADMIN;

CREATE OR REPLACE WAREHOUSE ACCOUNTING_WH
WITH WAREHOUSE_SIZE = MEDIUM MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 6 SCALING_POLICY = STANDARD;

ALTER SESSION SET USE_CACHED_RESULT = FALSE;

USE ROLE SYSADMIN;
ALTER SESSION SET USED_CACHE_RESULT = TRUE;
DROP WAREHOUSE CH2_WH;
DROP WAREHOUSE ACCOUNTING_WH;